# Cluster identity
ClusterName=localcluster
SlurmctldHost=master(192.168.100.10)

# Auth
AuthType=auth/munge
CryptoType=crypto/munge

# Scheduler
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

# Logging
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmctldPidFile=/var/run/slurm/slurmctld.pid
SlurmdPidFile=/var/run/slurm/slurmd.pid

# Dirs
StateSaveLocation=/var/spool/slurm
SlurmdSpoolDir=/var/spool/slurmd

# Timeouts
SlurmctldTimeout=300
SlurmdTimeout=300
InactiveLimit=0
MinJobAge=300
KillWait=30
Waittime=0

# Nodes — 16 CPUs each (1 socket, 8 cores, 2 threads per core)
NodeName=worker1 NodeAddr=192.168.100.11 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=8 ThreadsPerCore=2 RealMemory=4096 State=UNKNOWN
NodeName=worker2 NodeAddr=192.168.100.12 CPUs=16 Boards=1 SocketsPerBoard=1 CoresPerSocket=8 ThreadsPerCore=2 RealMemory=4096 State=UNKNOWN

# Partition
PartitionName=debug Nodes=worker1,worker2 Default=YES MaxTime=INFINITE State=UP

ProctrackType=proctrack/linuxproc
TaskPlugin=task/none
SlurmctldParameters=enable_configless

SlurmdParameters=enable_nss_slurm,sysconfdir=/etc/slurm
JobAcctGatherType=jobacct_gather/none

